require('dotenv').config();
const express = require('express');
const cors = require('cors');
const webpush = require('web-push');
const cron = require('node-cron');
const fs = require('fs');
const path = require('path');
const { HttpsProxyAgent } = require('https-proxy-agent');
const { createClient } = require('@supabase/supabase-js');

// Proxy for outbound API calls (set HTTPS_PROXY in .env, e.g. http://127.0.0.1:7897)
const OUTBOUND_PROXY = process.env.HTTPS_PROXY || process.env.HTTP_PROXY || null;
if (OUTBOUND_PROXY) {
  console.log('[proxy] Outbound proxy:', OUTBOUND_PROXY);
}

const app = express();
app.use(cors());
app.use(express.json());

const cookieParser = require('cookie-parser');
app.use(cookieParser());

// ==================== WEB PUSH SETUP ====================
// Trim + strip accidental quotes/newlines from Vercel env vars
let VAPID_PUBLIC_KEY = (process.env.VAPID_PUBLIC_KEY || '').trim().replace(/^["']|["']$/g, '');
let VAPID_PRIVATE_KEY = (process.env.VAPID_PRIVATE_KEY || '').trim().replace(/^["']|["']$/g, '');
const VAPID_SUBJECT = (process.env.VAPID_SUBJECT || 'mailto:warmbuddy@example.com').trim();
let vapidInitialized = false;
let vapidError = null;
let vapidAutoGenerated = false;

// Log key status for debugging (never log full private key)
console.log('[vapid] PUBLIC_KEY from env:', VAPID_PUBLIC_KEY ? `present (${VAPID_PUBLIC_KEY.length} chars)` : 'MISSING');
console.log('[vapid] PRIVATE_KEY from env:', VAPID_PRIVATE_KEY ? `present (${VAPID_PRIVATE_KEY.length} chars)` : 'MISSING');

// Helper: try to set up VAPID with given keys, returns {ok, error}
function trySetupVapid(publicKey, privateKey, subject) {
  try {
    webpush.setVapidDetails(subject, publicKey, privateKey);
    return { ok: true, error: null };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

// 1st attempt: use env-provided keys
if (VAPID_PUBLIC_KEY && VAPID_PRIVATE_KEY) {
  const result = trySetupVapid(VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT);
  if (result.ok) {
    vapidInitialized = true;
    console.log('🔔 Web Push initialized (env keys)');
  } else {
    console.error('❌ VAPID env keys failed:', result.error);
    console.error('   PUBLIC_KEY length:', VAPID_PUBLIC_KEY.length, 'chars, starts with:', VAPID_PUBLIC_KEY.slice(0, 8) + '...');
    console.error('   PRIVATE_KEY length:', VAPID_PRIVATE_KEY.length, 'chars');
    console.error('   SUBJECT:', VAPID_SUBJECT);
    // Don't reset — keep for diagnosis. Will try auto-generation as fallback.
    vapidError = result.error;
  }
}

// 2nd attempt: auto-generate if env keys are missing or invalid
if (!vapidInitialized) {
  const generated = webpush.generateVAPIDKeys();
  const genResult = trySetupVapid(generated.publicKey, generated.privateKey, VAPID_SUBJECT);
  if (genResult.ok) {
    VAPID_PUBLIC_KEY = generated.publicKey;
    VAPID_PRIVATE_KEY = generated.privateKey;
    vapidInitialized = true;
    vapidAutoGenerated = true;
    console.log('🔔 Web Push initialized (auto-generated keys)');
    console.log('   ⚠️  Auto-generated keys change on each deploy — subscriptions break.');
    console.log('   Add these to Vercel env vars for stability:');
    console.log('   VAPID_PUBLIC_KEY=' + VAPID_PUBLIC_KEY);
    console.log('   VAPID_PRIVATE_KEY=' + VAPID_PRIVATE_KEY);
  } else {
    console.error('❌ VAPID auto-generation also failed:', genResult.error);
    vapidError = (vapidError ? vapidError + '; ' : '') + 'Auto-gen also failed: ' + genResult.error;
  }
}

// In-memory push subscription store (single-user app)
let pushSubscription = null;

// Persist push subscription to Supabase (survives Render restarts)
async function loadPushSubscription() {
  if (!supabase) return null;
  try {
    const { data, error } = await supabase.from('app_state').select('value').eq('key', 'push_subscription').single();
    if (error || !data) return null;
    return data.value || null;
  } catch (e) { console.error('[supabase] loadPushSubscription error:', e.message); return null; }
}
async function savePushSubscription(sub) {
  if (!supabase) return;
  try {
    await supabase.from('app_state').upsert({ key: 'push_subscription', value: sub, updated_at: new Date().toISOString() }, { onConflict: 'key' });
  } catch (e) { console.error('[supabase] savePushSubscription error:', e.message); }
}

// ==================== AUTH MIDDLEWARE ====================
const ACCESS_PASSWORD = process.env.ACCESS_PASSWORD || 'mays2026';

app.use((req, res, next) => {
  if (req.path.startsWith('/api/') || req.cookies?.auth === 'true') {
    return next();
  }
  if (req.query.pwd === ACCESS_PASSWORD) {
    res.cookie('auth', 'true', { maxAge: 30 * 24 * 60 * 60 * 1000, httpOnly: true, sameSite: 'lax' });
    return res.redirect('/');
  }
  // Determine if this is a failed password attempt
  const showError = req.query.pwd !== undefined && req.query.pwd !== '';
  res.set('Cache-Control', 'no-store, no-cache, must-revalidate, private');
  return res.send(`
    <!DOCTYPE html>
    <html><head><meta charset="utf-8"><title>暖伴</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-store">
    <style>
      *{box-sizing:border-box;margin:0;padding:0;}
      body{background:#F7F5F1;display:flex;justify-content:center;align-items:center;height:100vh;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;}
      .box{text-align:center;padding:40px 32px;background:#fff;border-radius:16px;box-shadow:0 2px 16px rgba(0,0,0,0.06);max-width:360px;width:90%;}
      h2{font-size:18px;color:#4A4543;margin-bottom:20px;font-weight:500;letter-spacing:0.04em;}
      .row{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;}
      input{padding:12px 14px;border:1px solid #ddd;border-radius:10px;width:200px;font-size:15px;outline:none;transition:border 0.2s;}
      input:focus{border-color:#6B7C93;}
      button{padding:12px 24px;background:#6B7C93;color:white;border:none;border-radius:10px;font-size:15px;cursor:pointer;transition:background 0.2s;white-space:nowrap;}
      button:hover{background:#5A6B80;}
      .err{color:#C4877B;font-size:13px;margin-top:14px;display:${showError ? 'block' : 'none'};}
    </style>
    </head><body>
    <div class="box">
      <h2>🔐 暖伴 · 朝夕</h2>
      <form method="get">
        <div class="row">
          <input type="password" name="pwd" placeholder="输入访问密码" autofocus>
          <button type="submit">进入</button>
        </div>
      </form>
      <div class="err">❌ 密码不正确，请重试</div>
    </div>
    </body></html>
  `);
});

app.use(express.static('public'));

// ==================== MODEL REGISTRY ====================

/**
 * Central model registry: model ID → { provider, format, label, endpoint }
 * - provider: which company hosts the API (deepseek | anthropic | openai)
 * - format:   request/response format (anthropic | openai)
 * - endpoint: default API base URL for this model
 *
 * When the user sends a model ID, resolveModel() looks it up here.
 * Models fetched dynamically from the API (via /api/models or test-connection)
 * are merged into dynamicModels at runtime.
 */
const MODEL_REGISTRY = {
  // ── DeepSeek (OpenAI-compatible format) ──
  'deepseek-chat':     { provider:'deepseek', format:'openai',   label:'DeepSeek V4 Chat',      endpoint:'https://api.deepseek.com/v1/chat/completions' },
  'deepseek-reasoner': { provider:'deepseek', format:'openai',   label:'DeepSeek Reasoner',     endpoint:'https://api.deepseek.com/v1/chat/completions' },
  'deepseek-v4-pro':   { provider:'deepseek', format:'openai',   label:'DeepSeek V4 Pro',       endpoint:'https://api.deepseek.com/v1/chat/completions' },
  'deepseek-v4-flash': { provider:'deepseek', format:'openai',   label:'DeepSeek V4 Flash',     endpoint:'https://api.deepseek.com/v1/chat/completions' },

  // ── DeepSeek (Anthropic-compatible format) ──
  'deepseek-chat-a':   { provider:'deepseek', format:'anthropic',label:'DeepSeek Chat (Messages)',endpoint:'https://api.deepseek.com/anthropic/v1/messages' },

  // ── Anthropic native ──
  'claude-sonnet-4-6': { provider:'anthropic',format:'anthropic',label:'Claude Sonnet 4.6',     endpoint:'https://api.anthropic.com/v1/messages' },
  'claude-opus-4-8':   { provider:'anthropic',format:'anthropic',label:'Claude Opus 4.8',       endpoint:'https://api.anthropic.com/v1/messages' },
  'claude-haiku-4-5':  { provider:'anthropic',format:'anthropic',label:'Claude Haiku 4.5',      endpoint:'https://api.anthropic.com/v1/messages' },

  // ── OpenAI ──
  'gpt-4o':            { provider:'openai',   format:'openai',   label:'GPT-4o',                endpoint:'https://api.openai.com/v1/chat/completions' },
  'gpt-4o-mini':       { provider:'openai',   format:'openai',   label:'GPT-4o Mini',           endpoint:'https://api.openai.com/v1/chat/completions' },
  'gpt-4-turbo':       { provider:'openai',   format:'openai',   label:'GPT-4 Turbo',           endpoint:'https://api.openai.com/v1/chat/completions' },

  // ── OpenRouter (OpenAI-compatible format) ──
  'openai/gpt-4o':              { provider:'openrouter', format:'openai', label:'GPT-4o (OpenRouter)',              endpoint:'https://openrouter.ai/api/v1/chat/completions' },
  'anthropic/claude-sonnet-4-6':{ provider:'openrouter', format:'openai', label:'Claude Sonnet 4.6 (OpenRouter)',   endpoint:'https://openrouter.ai/api/v1/chat/completions' },
  'google/gemini-2.5-pro':      { provider:'openrouter', format:'openai', label:'Gemini 2.5 Pro (OpenRouter)',      endpoint:'https://openrouter.ai/api/v1/chat/completions' },
  'deepseek/deepseek-chat':     { provider:'openrouter', format:'openai', label:'DeepSeek Chat (OpenRouter)',       endpoint:'https://openrouter.ai/api/v1/chat/completions' },
  'meta-llama/llama-4-maverick':{ provider:'openrouter', format:'openai', label:'Llama 4 Maverick (OpenRouter)',    endpoint:'https://openrouter.ai/api/v1/chat/completions' },

  // ── ZhipuAI GLM (OpenAI-compatible format) ──
  'glm-4-plus':  { provider:'glm', format:'openai', label:'GLM-4 Plus',  endpoint:'https://open.bigmodel.cn/api/paas/v4/chat/completions' },
  'glm-4-flash': { provider:'glm', format:'openai', label:'GLM-4 Flash', endpoint:'https://open.bigmodel.cn/api/paas/v4/chat/completions' },
  'glm-4':       { provider:'glm', format:'openai', label:'GLM-4',       endpoint:'https://open.bigmodel.cn/api/paas/v4/chat/completions' },
  'glm-4-air':   { provider:'glm', format:'openai', label:'GLM-4 Air',   endpoint:'https://open.bigmodel.cn/api/paas/v4/chat/completions' },
};

// Runtime cache for models fetched dynamically from APIs
const dynamicModels = {};

/**
 * Resolve a model ID to its provider, format, and endpoint.
 * @param {string} model - Model ID (e.g. "deepseek-chat", "claude-sonnet-4-6")
 * @param {string} [userEndpoint] - User-configured endpoint override
 * @returns {{ provider:string, format:string, endpoint:string, label:string }}
 */
function resolveModel(model, userEndpoint) {
  // 1. Check static registry + dynamic models
  const entry = MODEL_REGISTRY[model] || dynamicModels[model];
  if (entry) {
    // If user provides a custom endpoint, detect format from it
    const format = userEndpoint ? detectProvider(userEndpoint) : entry.format;
    const endpoint = userEndpoint || entry.endpoint;
    // Provider follows the actual host when endpoint is overridden
    let provider = entry.provider;
    if (userEndpoint) {
      const host = userEndpoint.toLowerCase();
      if (host.includes('deepseek')) provider = 'deepseek';
      else if (host.includes('openai')) provider = 'openai';
      else if (host.includes('anthropic')) provider = 'anthropic';
    }
    return { provider, format, endpoint, label: entry.label || entry.id || model };
  }
  // 2. Unknown model — infer from user endpoint or default to OpenAI
  const format = userEndpoint ? detectProvider(userEndpoint) : 'openai';
  const endpoint = userEndpoint || 'https://api.openai.com/v1/chat/completions';
  let provider = 'openai';
  if (format === 'anthropic') provider = 'anthropic';
  else if (userEndpoint && userEndpoint.toLowerCase().includes('deepseek')) provider = 'deepseek';
  return { provider, format, endpoint, label: model };
}

// ==================== API HELPERS ====================

/**
 * Safe fetch wrapper — uses native https module for openrouter.ai domains
 * to work around a Node.js undici bug where the Authorization header is
 * silently dropped for certain hosts (HTTP/2 ALPN negotiation issue).
 * All other domains use the standard global fetch().
 *
 * @param {string} url - Full URL to fetch
 * @param {object} opts - { method, headers, body?, stream? }
 *   stream: if true, returns a response with body.getReader() for SSE streaming
 * @returns {Promise<{ok:boolean, status:number, text:()=>Promise<string>, json:()=>Promise<any>, body?:{getReader:fn}}>}
 */
async function safeFetch(url, opts = {}) {
  if (!url.toLowerCase().includes('openrouter')) {
    return fetch(url, opts);
  }

  // Native https for OpenRouter — undici drops Authorization header
  const https = require('https');
  const u = new URL(url);
  const { method = 'GET', headers = {}, body, stream } = opts;

  console.log(`[safe-fetch] Native HTTPS ${method} ${u.hostname}${u.pathname} stream=${!!stream}`);

  return new Promise((resolve, reject) => {
    const reqOpts = {
      hostname: u.hostname,
      path: u.pathname + u.search,
      method,
      headers: { ...headers, 'User-Agent': 'WarmBuddy/1.0' }
    };
    // Route through proxy if configured
    if (OUTBOUND_PROXY) {
      reqOpts.agent = new HttpsProxyAgent(OUTBOUND_PROXY);
    }
    const req = https.request(reqOpts, (resp) => {
      const respHeaders = {};
      for (const [k, v] of Object.entries(resp.headers)) {
        respHeaders[k] = Array.isArray(v) ? v.join(', ') : v;
      }

      if (stream) {
        // Streaming mode: build a ReadableStream from the native response
        const rs = new ReadableStream({
          start(controller) {
            resp.on('data', chunk => controller.enqueue(chunk));
            resp.on('end', () => controller.close());
            resp.on('error', err => controller.error(err));
          },
          cancel() { resp.destroy(); }
        });
        resolve({
          ok: resp.statusCode >= 200 && resp.statusCode < 300,
          status: resp.statusCode,
          headers: new Map(Object.entries(respHeaders)),
          body: rs  // has getReader() natively
        });
      } else {
        // Non-streaming: buffer entire body
        const chunks = [];
        resp.on('data', chunk => chunks.push(chunk));
        resp.on('end', () => {
          const rawBody = Buffer.concat(chunks).toString('utf-8');
          resolve({
            ok: resp.statusCode >= 200 && resp.statusCode < 300,
            status: resp.statusCode,
            headers: new Map(Object.entries(respHeaders)),
            text: () => Promise.resolve(rawBody),
            json: () => Promise.resolve(JSON.parse(rawBody))
          });
        });
      }
    });

    req.on('error', (err) => reject(err));

    if (body) {
      req.write(body);
    }
    req.end();
  });
}

/**
 * Detect API format from endpoint URL.
 * Uses PATH structure first (most reliable), then domain fallback.
 */
function detectProvider(endpoint) {
  if (!endpoint) return 'anthropic';
  const url = endpoint.toLowerCase();
  // Path-based detection (most reliable — different APIs use different path patterns)
  // Anthropic Messages API: /v1/messages or /anthropic/v1/messages
  if (url.includes('/messages') && !url.includes('/chat/completions')) return 'anthropic';
  // OpenAI Chat Completions API: /v1/chat/completions
  if (url.includes('/chat/completions')) return 'openai';
  // Domain-based fallback
  if (url.includes('anthropic') || url.includes('claude')) return 'anthropic';
  if (url.includes('deepseek')) return 'deepseek';
  if (url.includes('openai') || url.includes('openrouter')) return 'openai';
  return 'openai';
}

/**
 * Build auth headers based on provider format and actual host.
 * DeepSeek always uses Bearer token even for Anthropic-format endpoints.
 */
function getAuthHeaders(provider, endpoint, apiKey) {
  const host = (endpoint || '').toLowerCase();
  const key = (apiKey || '').trim();

  // DeepSeek-hosted APIs always use Bearer auth
  if (host.includes('deepseek')) {
    return { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}` };
  }
  // Standard Anthropic auth
  if (provider === 'anthropic') {
    return { 'Content-Type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' };
  }
  // OpenRouter uses Bearer auth + recommended headers
  if (host.includes('openrouter') || provider === 'openrouter') {
    const headers = {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${key}`,
      'HTTP-Referer': 'https://warmbuddy.vercel.app',
      'X-Title': 'WarmBuddy'
    };
    return headers;
  }
  // Standard OpenAI-compatible auth (GLM, OpenAI, etc.)
  return { 'Content-Type': 'application/json', 'Authorization': `Bearer ${key}` };
}

/**
 * Build request body based on provider
 */
function buildRequestBody(provider, model, messages, stream) {
  switch (provider) {
    case 'anthropic': {
      // Convert messages format for Anthropic
      const systemMsg = messages.find(m => m.role === 'system');
      const chatMessages = messages.filter(m => m.role !== 'system');
      const body = {
        model: model || 'claude-sonnet-4-6',
        max_tokens: 4096,
        messages: chatMessages.map(m => ({
          role: m.role === 'ai' ? 'assistant' : m.role,
          content: m.content
        })),
        stream: stream
      };
      if (systemMsg) body.system = systemMsg.content;
      return body;
    }
    case 'deepseek':
    case 'openai':
    default: {
      return {
        model: model || (provider === 'deepseek' ? 'deepseek-chat' : 'gpt-4o'),
        messages: messages.map(m => ({
          role: m.role === 'ai' ? 'assistant' : m.role,
          content: m.content
        })),
        stream: stream,
        max_tokens: 4096
      };
    }
  }
}

/**
 * Parse a single SSE chunk for each provider
 */
function parseStreamChunk(provider, chunk) {
  switch (provider) {
    case 'anthropic': {
      try {
        const json = JSON.parse(chunk);
        // Handle error events
        if (json.type === 'error') {
          return { error: json.error?.message || JSON.stringify(json.error) };
        }
        if (json.type === 'content_block_delta' && json.delta?.text != null) {
          return { text: json.delta.text };
        }
        if (json.type === 'message_start' && json.message?.usage) {
          return { usage: json.message.usage };
        }
        if (json.type === 'message_delta' && json.usage) {
          return { usage: json.usage };
        }
        return null;
      } catch { return null; }
    }
    case 'deepseek':
    case 'openai':
    default: {
      try {
        const json = JSON.parse(chunk);
        // Handle error events
        if (json.error) {
          return { error: json.error.message || JSON.stringify(json.error) };
        }
        if (json.choices && json.choices[0]?.delta?.content != null) {
          const result = { text: json.choices[0].delta.content };
          if (json.usage) result.usage = json.usage;
          return result;
        }
        if (json.usage) {
          return { usage: json.usage };
        }
        return null;
      } catch { return null; }
    }
  }
}

/**
 * Extract full response content from non-streaming response
 */
function extractResponseContent(provider, data) {
  // Check for API error in response body first
  if (data.error) {
    const errMsg = data.error.message || JSON.stringify(data.error);
    return { content: '', error: errMsg, usage: null };
  }
  switch (provider) {
    case 'anthropic': {
      if (data.content && Array.isArray(data.content)) {
        return {
          content: data.content.map(c => c.text || '').join(''),
          usage: data.usage || null
        };
      }
      return { content: '', usage: null };
    }
    case 'deepseek':
    case 'openai':
    default: {
      if (data.choices && data.choices[0]?.message?.content != null) {
        return {
          content: data.choices[0].message.content,
          usage: data.usage || null
        };
      }
      return { content: '', usage: null };
    }
  }
}

// ==================== PROJECT CONFIGS + SYSTEM EVENTS ====================
const DATA_DIR = process.env.RENDER_DISK_MOUNT_PATH || path.join(__dirname, 'data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
const CONFIGS_FILE = path.join(DATA_DIR, 'projectConfigs.json');
const EVENTS_FILE = path.join(DATA_DIR, 'systemEvents.json');

// ── Supabase client (project configs persisted in DB, not ephemeral filesystem) ──
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_KEY = process.env.SUPABASE_KEY || '';
let supabase = null;
if (SUPABASE_URL && SUPABASE_KEY) {
  supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
    db: { schema: 'public' },
    // Disable realtime WebSocket — we only use DB queries, not subscriptions
    realtime: { enabled: false }
  });
  console.log('[supabase] Connected to:', SUPABASE_URL);
  // Restore push subscription + email config from DB (survives Render restarts)
  loadPushSubscription().then(function(sub) {
    if (sub) { pushSubscription = sub; console.log('[push] Subscription restored from Supabase'); }
  }).catch(function(){});
  loadEmailConfig().then(function(cfg) {
    if (cfg) {
      emailState.recipient = cfg.recipient || '';
      emailState.senderName = cfg.senderName || 'WarmBuddy';
      emailState.enabled = cfg.enabled !== false;
      emailState.maxPerDay = cfg.maxPerDay || 2;
      console.log('[email] Config restored from Supabase');
    }
  }).catch(function(){});
} else {
  console.log('[supabase] NOT configured — falling back to file-based configs');
}

// In-memory config cache (reduces Supabase roundtrips for cron)
let _configsCache = null;
let _configsCacheTime = 0;
const CONFIGS_CACHE_TTL = 15000; // 15s

async function loadProjectConfigs() {
  if (supabase) {
    try {
      // Use cache if fresh
      if (_configsCache && (Date.now() - _configsCacheTime) < CONFIGS_CACHE_TTL) {
        return _configsCache;
      }
      const { data, error } = await supabase.from('project_configs').select('project_id, config');
      if (error) throw error;
      const configs = {};
      for (const row of (data || [])) {
        configs[row.project_id] = row.config || {};
      }
      _configsCache = configs;
      _configsCacheTime = Date.now();
      return configs;
    } catch (e) {
      console.error('[supabase] loadProjectConfigs error:', e.message);
      // Fallback to file on error
    }
  }
  // File-based fallback
  try { return JSON.parse(fs.readFileSync(CONFIGS_FILE, 'utf-8')); } catch { return {}; }
}

async function saveProjectConfigs(configs) {
  // Update cache
  _configsCache = configs;
  _configsCacheTime = Date.now();

  if (supabase) {
    try {
      const rows = Object.entries(configs).map(([pid, cfg]) => ({
        project_id: pid,
        config: cfg,
        updated_at: new Date().toISOString()
      }));
      if (rows.length === 0) return;
      const { error } = await supabase.from('project_configs').upsert(rows, { onConflict: 'project_id' });
      if (error) throw error;
      return;
    } catch (e) {
      console.error('[supabase] saveProjectConfigs error:', e.message);
      // Fallback to file on error
    }
  }
  // File-based fallback
  fs.writeFileSync(CONFIGS_FILE, JSON.stringify(configs, null, 2), 'utf-8');
}

/**
 * Atomically save ONLY the desire-state-related fields to Supabase.
 * Uses the PostgreSQL RPC function atomic_update_desire_state which does
 * jsonb || jsonb_build_object — only touches _desireState, _lastBackendGrowth,
 * _lastTriggerTime, _lastTriggerDrive. Other keys (apiKey, endpoint, etc.)
 * are left untouched, eliminating read-modify-write races with frontend syncs.
 *
 * Falls back to full saveProjectConfigs when Supabase is not configured.
 */
async function saveDesireStateOnly(pid, desireState, lastBackendGrowth, triggerInfo) {
  if (supabase) {
    try {
      // Single JSONB payload — avoids Supabase RPC alphabetic parameter reordering
      const { error } = await supabase.rpc('atomic_update_desire_state', {
        payload: {
          p_project_id: pid,
          p_desire_state: desireState,
          p_last_backend_growth: lastBackendGrowth,
          p_last_trigger_time: triggerInfo?.lastTriggerTime || '',
          p_last_trigger_drive: triggerInfo?.lastTriggerDrive || ''
        }
      });
      if (error) throw error;

      // Update in-memory cache for this project
      if (_configsCache && _configsCache[pid]) {
        _configsCache[pid]._desireState = desireState;
        _configsCache[pid]._lastBackendGrowth = lastBackendGrowth;
        if (triggerInfo?.lastTriggerTime) _configsCache[pid]._lastTriggerTime = triggerInfo.lastTriggerTime;
        if (triggerInfo?.lastTriggerDrive) _configsCache[pid]._lastTriggerDrive = triggerInfo.lastTriggerDrive;
      }
      return;
    } catch (e) {
      console.error('[supabase] saveDesireStateOnly error:', e.message);
      // Fall through to file-based fallback
    }
  }

  // File-based fallback: full save (no concurrency concern without Supabase)
  const configs = await loadProjectConfigs();
  if (!configs[pid]) configs[pid] = {};
  configs[pid]._desireState = desireState;
  configs[pid]._lastBackendGrowth = lastBackendGrowth;
  if (triggerInfo?.lastTriggerTime) configs[pid]._lastTriggerTime = triggerInfo.lastTriggerTime;
  if (triggerInfo?.lastTriggerDrive) configs[pid]._lastTriggerDrive = triggerInfo.lastTriggerDrive;
  await saveProjectConfigs(configs);
}

// project config: { [pid]: { apiKey, endpoint, model, enabled, recipient?, emailEnabled?: true, emailMaxPerDay?: 2, emailSentToday?: 0, emailSentDate?: '', _desireState?: { drives, lastCheck }, _lastBackendGrowth?, _lastTriggerTime?, _lastTriggerDrive?, _chatId?: '' } }
// system events: [{ id, projectId, chatId, type: 'message'|'todo'|'email'|'litter'|'diary'|'todo_wake', driveKey?, content, timestamp, pushSent: false, todoId?, todoTitle? }]

// ── To-Do persistence (Supabase project_todos table) ──
async function loadTodos(projectId) {
  if (!supabase) return [];
  try {
    const { data } = await supabase.from('project_todos')
      .select('*').eq('project_id', projectId);
    return data || [];
  } catch (e) { console.error('[supabase] loadTodos error:', e.message); return []; }
}

async function saveTodos(projectId, todos) {
  if (!supabase) return;
  try {
    await supabase.from('project_todos').delete().eq('project_id', projectId);
    if (todos.length > 0) {
      const rows = todos.map(t => ({
        id: t.id, project_id: projectId, chat_id: t.chat_id || t.chatId || '',
        title: t.title, time: t.time, creator: t.creator || 'user',
        triggered: t.triggered || false, done: t.done || false,
        created_at: t.createdAt || t.created_at || new Date().toISOString()
      }));
      await supabase.from('project_todos').insert(rows);
    }
  } catch (e) { console.error('[supabase] saveTodos error:', e.message); }
}

async function countAITodosToday(projectId) {
  if (!supabase) return 0;
  try {
    const today = new Date().toISOString().slice(0, 10);
    const { count } = await supabase.from('project_todos')
      .select('*', { count: 'exact', head: true })
      .eq('project_id', projectId)
      .eq('creator', 'ai')
      .gte('created_at', today + 'T00:00:00Z')
      .lte('created_at', today + 'T23:59:59Z');
    return count || 0;
  } catch (e) { return 0; }
}

function loadSystemEvents() {
  try { return JSON.parse(fs.readFileSync(EVENTS_FILE, 'utf-8')); } catch { return []; }
}
function saveSystemEvents(events) {
  // Keep last 200 events max
  if (events.length > 200) events = events.slice(-200);
  fs.writeFileSync(EVENTS_FILE, JSON.stringify(events, null, 2), 'utf-8');
}

// ==================== API ENDPOINTS ====================

/**
 * POST /api/test-connection
 * Body: { apiKey, endpoint, model? }
 * Tests connectivity to the LLM API and returns available models
 */
app.post('/api/test-connection', async (req, res) => {
  const b = req.body || {};
  const { apiKey, endpoint, model: preferredModel } = b;
  if (!apiKey) return res.status(400).json({ error: 'Missing API key' });

  // Resolve model to determine format + endpoint for the test call
  const testModel = preferredModel || 'deepseek-chat';
  const resolved = resolveModel(testModel, endpoint);
  const format = resolved.format;
  const fetchUrl = resolved.endpoint;

  console.log(`[test-conn] model=${testModel} format=${format} provider=${resolved.provider} endpoint=${fetchUrl}`);

  try {
    // Use a minimal test message to verify connection
    const testBody = buildRequestBody(format, testModel, [
      { role: 'user', content: 'Hi' }
    ], false);

    // Set max_tokens minimal for test
    testBody.max_tokens = 10;

    const headers = getAuthHeaders(resolved.provider, resolved.endpoint, apiKey);
    // Debug: log headers (mask API key)
    const debugHeaders = {};
    for (const [k, v] of Object.entries(headers)) {
      debugHeaders[k] = (k === 'Authorization' || k === 'x-api-key')
        ? v.slice(0, 15) + '...[masked]'
        : v;
    }
    console.log(`[test-conn] request headers:`, JSON.stringify(debugHeaders));
    console.log(`[test-conn] request body model:`, testBody.model);

    // === OpenRouter: pre-check auth with /api/v1/auth/key ===
    if (fetchUrl.includes('openrouter') || resolved.provider === 'openrouter') {
      const key = (apiKey || '').trim();
      console.log(`[test-conn] OpenRouter auth pre-check (safeFetch)`);
      try {
        const authResp = await safeFetch('https://openrouter.ai/api/v1/auth/key', {
          headers: { 'Authorization': `Bearer ${key}` }
        });
        const authText = await authResp.text();
        console.log(`[test-conn] Auth check status: ${authResp.status}`);
        if (!authResp.ok) {
          let authErr = authText;
          try { const ej = JSON.parse(authText); authErr = ej.error?.message || ej.error?.code || authText; } catch {}
          return res.json({
            success: false, provider: resolved.provider, format,
            message: `OpenRouter auth failed (${authResp.status}): ${authErr}`
          });
        }
        console.log(`[test-conn] OpenRouter auth OK ✓`);
      } catch (authErr) {
        console.error(`[test-conn] Auth check error:`, authErr.message);
        return res.json({
          success: false, provider: resolved.provider, format,
          message: `OpenRouter auth check error: ${authErr.message}`
        });
      }
    }

    const response = await safeFetch(fetchUrl, {
      method: 'POST',
      headers,
      body: JSON.stringify(testBody)
    });

    if (!response.ok) {
      const errText = await response.text();
      let errMsg = errText;
      try { const ej = JSON.parse(errText); errMsg = ej.error?.message || ej.error?.code || errText; } catch {}
      // Detailed debug for auth failures
      console.error(`[test-conn] UPSTREAM ERROR: status=${response.status}`);
      console.error(`[test-conn] Raw body (first 500 chars):`, errText.slice(0, 500));
      console.error(`[test-conn] Resolved: provider=${resolved.provider} format=${format} fetchUrl=${fetchUrl}`);
      return res.json({
        success: false,
        provider: resolved.provider,
        format,
        message: `Connection failed (${response.status}): ${errMsg}`
      });
    }

    // Connection works — now try to get available models
    let models = [];
    try {
      models = await fetchAvailableModels(resolved.provider, resolved.endpoint, apiKey);
      // Register fetched models in dynamicModels for resolveModel()
      for (const m of models) {
        if (!MODEL_REGISTRY[m.id] && !dynamicModels[m.id]) {
          dynamicModels[m.id] = {
            provider: resolved.provider,
            format,
            label: m.label || m.id,
            endpoint: resolved.endpoint
          };
        }
      }
    } catch (modelErr) {
      console.log('Could not fetch models list, using defaults:', modelErr.message);
      models = getDefaultModels(format, resolved.provider);
    }

    res.json({
      success: true,
      provider: resolved.provider,
      format,
      message: 'Connection successful',
      models
    });
  } catch (err) {
    console.error('Test connection error:', err);
    res.json({
      success: false,
      provider: null,
      format: null,
      message: `Network error: ${err.message}`
    });
  }
});

/**
 * Fetch available models from the provider API
 */
async function fetchAvailableModels(provider, endpoint, apiKey) {
  const host = (endpoint || '').toLowerCase();

  // Determine models URL based on actual API host
  let modelsUrl;
  if (host.includes('deepseek')) {
    modelsUrl = 'https://api.deepseek.com/v1/models';
  } else if (host.includes('openai')) {
    modelsUrl = 'https://api.openai.com/v1/models';
  } else if (host.includes('openrouter')) {
    modelsUrl = 'https://openrouter.ai/api/v1/models';
  } else if (host.includes('anthropic') || host.includes('claude')) {
    modelsUrl = 'https://api.anthropic.com/v1/models?limit=50';
  } else if (provider === 'anthropic') {
    modelsUrl = 'https://api.anthropic.com/v1/models?limit=50';
  } else {
    // OpenAI-compatible: extract base URL from endpoint path
    const base = host
      ? endpoint.replace(/\/chat\/completions\/?$/, '').replace(/\/v1\/.*$/, '/v1')
      : 'https://api.openai.com/v1';
    modelsUrl = `${base}/models`;
  }

  const headers = getAuthHeaders(provider, endpoint, apiKey);

  const resp = await safeFetch(modelsUrl, { headers });
  if (!resp.ok) throw new Error(`Models fetch failed: ${resp.status}`);

  const data = await resp.json();

  // Different providers return different structures
  if (provider === 'anthropic' && data.data) {
    return data.data
      .filter(m => m.id && m.id.includes('claude'))
      .map(m => ({ id: m.id, label: m.display_name || m.id }));
  }

  if (data.data && Array.isArray(data.data)) {
    // OpenAI format: { data: [{ id, ... }] }
    return data.data
      .filter(m => m.id && !m.id.includes('whisper') && !m.id.includes('tts') &&
        !m.id.includes('dall-e') && !m.id.includes('embedding') && !m.id.includes('moderation'))
      .map(m => ({ id: m.id, label: m.id }));
  }

  throw new Error('Unexpected models response');
}

function getDefaultModels(format, provider) {
  // Build models list from MODEL_REGISTRY filtered by provider
  const registryModels = Object.entries(MODEL_REGISTRY)
    .filter(([id, entry]) => entry.provider === provider)
    .map(([id, entry]) => ({ id, label: entry.label }));

  if (registryModels.length > 0) return registryModels;

  // Fallback defaults
  switch (provider) {
    case 'anthropic':
      return [
        { id: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6' },
        { id: 'claude-opus-4-8', label: 'Claude Opus 4.8' },
        { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5' },
      ];
    case 'deepseek':
      return [
        { id: 'deepseek-chat', label: 'DeepSeek V4 Chat' },
        { id: 'deepseek-v4-pro', label: 'DeepSeek V4 Pro' },
        { id: 'deepseek-v4-flash', label: 'DeepSeek V4 Flash' },
        { id: 'deepseek-reasoner', label: 'DeepSeek Reasoner' },
      ];
    case 'openai':
    default:
      return [
        { id: 'gpt-4o', label: 'GPT-4o' },
        { id: 'gpt-4o-mini', label: 'GPT-4o Mini' },
        { id: 'gpt-4-turbo', label: 'GPT-4 Turbo' },
      ];
  }
}

/**
 * POST /api/models
 * Body: { apiKey, endpoint }
 * Fetch available models from the provider
 */
app.post('/api/models', async (req, res) => {
  const b = req.body || {};
  const { apiKey, endpoint } = b;
  if (!apiKey) return res.status(400).json({ error: 'Missing API key' });

  const format = detectProvider(endpoint);
  const host = (endpoint || '').toLowerCase();
  let provider = format;
  if (host.includes('deepseek')) provider = 'deepseek';
  else if (host.includes('openrouter')) provider = 'openrouter';
  else if (host.includes('bigmodel')) provider = 'glm';
  else if (host.includes('anthropic')) provider = 'anthropic';
  else if (host.includes('openai')) provider = 'openai';

  try {
    const models = await fetchAvailableModels(provider, endpoint, apiKey);
    // Register in dynamicModels
    for (const m of models) {
      if (!MODEL_REGISTRY[m.id] && !dynamicModels[m.id]) {
        dynamicModels[m.id] = { provider, format, label: m.label || m.id, endpoint };
      }
    }
    res.json({ success: true, provider, format, models });
  } catch (err) {
    console.error('Fetch models error:', err);
    res.json({ success: true, provider, format, models: getDefaultModels(format, provider) });
  }
});

/**
 * GET /api/presets
 * Returns provider presets and the full model registry for the frontend.
 */
app.get('/api/presets', (req, res) => {
  const presets = [
    {
      id: 'deepseek-openai', label: 'DeepSeek (OpenAI 格式)',
      endpoint: 'https://api.deepseek.com/v1/chat/completions',
      provider: 'deepseek', format: 'openai',
      models: Object.keys(MODEL_REGISTRY).filter(k => MODEL_REGISTRY[k].provider === 'deepseek' && MODEL_REGISTRY[k].format === 'openai')
    },
    {
      id: 'deepseek-anthropic', label: 'DeepSeek (Anthropic 格式)',
      endpoint: 'https://api.deepseek.com/anthropic/v1/messages',
      provider: 'deepseek', format: 'anthropic',
      models: Object.keys(MODEL_REGISTRY).filter(k => MODEL_REGISTRY[k].provider === 'deepseek' && MODEL_REGISTRY[k].format === 'anthropic')
    },
    {
      id: 'anthropic', label: 'Anthropic 原生',
      endpoint: 'https://api.anthropic.com/v1/messages',
      provider: 'anthropic', format: 'anthropic',
      models: Object.keys(MODEL_REGISTRY).filter(k => MODEL_REGISTRY[k].provider === 'anthropic')
    },
    {
      id: 'openai', label: 'OpenAI',
      endpoint: 'https://api.openai.com/v1/chat/completions',
      provider: 'openai', format: 'openai',
      models: Object.keys(MODEL_REGISTRY).filter(k => MODEL_REGISTRY[k].provider === 'openai')
    },
    {
      id: 'openrouter', label: 'OpenRouter',
      endpoint: 'https://openrouter.ai/api/v1/chat/completions',
      provider: 'openrouter', format: 'openai',
      models: Object.keys(MODEL_REGISTRY).filter(k => MODEL_REGISTRY[k].provider === 'openrouter')
    },
    {
      id: 'glm', label: '智谱 GLM',
      endpoint: 'https://open.bigmodel.cn/api/paas/v4/chat/completions',
      provider: 'glm', format: 'openai',
      models: Object.keys(MODEL_REGISTRY).filter(k => MODEL_REGISTRY[k].provider === 'glm')
    }
  ];

  const modelList = {};
  for (const [id, entry] of Object.entries(MODEL_REGISTRY)) {
    modelList[id] = { label: entry.label, provider: entry.provider, format: entry.format, endpoint: entry.endpoint };
  }

  res.json({ presets, models: modelList });
});

/**
 * POST /api/chat/stream
 * Body: { apiKey, endpoint, model, messages }
 * Response: SSE stream
 */
app.post('/api/chat/stream', async (req, res) => {
  try {
    // Null-safety: req.body may be undefined if body-parser skipped
    const body = req.body || {};
    const { apiKey, endpoint, model, messages } = body;

    if (!apiKey) return res.status(400).json({ error: 'Missing API key' });
    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: 'Missing messages' });
    }

    // Resolve model → provider + format + endpoint
    const resolved = resolveModel(model, endpoint);
    const format = resolved.format;
    const fetchUrl = resolved.endpoint;

    console.log(`[chat/stream] model=${model} format=${format} provider=${resolved.provider} endpoint=${fetchUrl}`);

    // Set up SSE headers (Express 5 compatible way)
    res.status(200);
    res.set({
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
      'X-Accel-Buffering': 'no'
    });
    res.flushHeaders();

    const headers = getAuthHeaders(resolved.provider, resolved.endpoint, apiKey);
    const requestBody = buildRequestBody(format, model, messages, true);

    const response = await safeFetch(fetchUrl, {
      method: 'POST',
      headers,
      body: JSON.stringify(requestBody),
      stream: true
    });

    console.log(`[chat/stream] upstream status=${response.status}`);

    if (!response.ok) {
      const errText = await response.text();
      let errMsg = errText;
      try { const ej = JSON.parse(errText); errMsg = ej.error?.message || ej.error?.code || errText; } catch {}
      console.error(`[chat/stream] upstream error: ${errMsg}`);
      res.write(`data: ${JSON.stringify({ error: `API error (${response.status}): ${errMsg}` })}\n\n`);
      res.end();
      return;
    }

    // Stream the response
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    let chunkCount = 0;
    let totalLines = 0;
    let skippedLines = 0;
    const DEBUG_STREAM = process.env.DEBUG_STREAM === 'true';

    // Save raw stream for debugging
    let rawStreamBuf = DEBUG_STREAM ? '' : null;

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      const decoded = decoder.decode(value, { stream: true });
      buffer += decoded;
      if (DEBUG_STREAM) rawStreamBuf += decoded;

      // Handle both \r\n and \n line endings
      const lines = buffer.split(/\r?\n/);
      buffer = lines.pop() || '';

      for (const line of lines) {
        totalLines++;
        const trimmed = line.trim();
        if (!trimmed) continue;

        if (trimmed === '[DONE]' || trimmed === 'data: [DONE]') {
          if (DEBUG_STREAM) console.log(`[chat/stream] [DONE] marker found`);
          res.write(`data: [DONE]\n\n`);
          continue;
        }

        let data = trimmed;
        if (trimmed.startsWith('data: ')) {
          data = trimmed.slice(6);
        } else {
          // Non-data line (e.g., event: ...)
          if (DEBUG_STREAM) console.log(`[chat/stream] non-data line: ${trimmed.slice(0, 100)}`);
          skippedLines++;
          continue;
        }

        const parsed = parseStreamChunk(format, data);
        if (parsed) {
          chunkCount++;
          if (DEBUG_STREAM) console.log(`[chat/stream] chunk #${chunkCount}:`, JSON.stringify(parsed).slice(0, 120));
          res.write(`data: ${JSON.stringify(parsed)}\n\n`);
        } else if (DEBUG_STREAM) {
          // Log what wasn't parsed
          console.log(`[chat/stream] unparsed data line: ${data.slice(0, 200)}`);
        }
      }
    }

    // Handle remaining buffer
    if (buffer.trim()) {
      let data = buffer.trim();
      if (data.startsWith('data: ')) data = data.slice(6);
      if (data !== '[DONE]' && data !== 'data: [DONE]') {
        const parsed = parseStreamChunk(format, data);
        if (parsed) {
          chunkCount++;
          if (DEBUG_STREAM) console.log(`[chat/stream] chunk #${chunkCount} (buffer):`, JSON.stringify(parsed).slice(0, 120));
          res.write(`data: ${JSON.stringify(parsed)}\n\n`);
        } else if (DEBUG_STREAM) {
          console.log(`[chat/stream] unparsed buffer: ${data.slice(0, 200)}`);
        }
      }
    }

    console.log(`[chat/stream] total=${totalLines} lines, skipped=${skippedLines} non-data, forwarded=${chunkCount} chunks, format=${format}`);

    // If very few chunks, log raw response for debugging
    if (chunkCount < 2) {
      const rawSample = rawStreamBuf ? rawStreamBuf.slice(0, 1200) : '(set DEBUG_STREAM=true to capture)';
      console.log(`[chat/stream] WARNING: only ${chunkCount} chunk(s) forwarded. Raw sample:`, rawSample);

      // Handle non-SSE response: API might have returned raw JSON despite stream=true
      if (rawStreamBuf && rawStreamBuf.trim().startsWith('{')) {
        console.log(`[chat/stream] Detected non-SSE response (raw JSON), attempting to parse...`);
        try {
          const trimmed = rawStreamBuf.trim();
          const json = JSON.parse(trimmed);
          const result = extractResponseContent(format, json);
          if (result.error) {
            res.write(`data: ${JSON.stringify({ error: result.error })}\n\n`);
          } else if (result.content) {
            res.write(`data: ${JSON.stringify({ text: result.content })}\n\n`);
            if (result.usage) {
              res.write(`data: ${JSON.stringify({ usage: result.usage })}\n\n`);
            }
            chunkCount++;
            console.log(`[chat/stream] Non-SSE fallback extracted content (${result.content.length} chars)`);
          }
        } catch (e) {
          console.log(`[chat/stream] Non-SSE parse failed: ${e.message}`);
        }
      }
    }

    if (DEBUG_STREAM && rawStreamBuf) {
      console.log(`[chat/stream] === RAW STREAM (first 2000 chars) ===`);
      console.log(rawStreamBuf.slice(0, 2000));
      console.log(`[chat/stream] === RAW STREAM END (total ${rawStreamBuf.length} chars) ===`);
    }

    // If no chunks were forwarded, try non-streaming fallback
    if (chunkCount === 0) {
      console.log(`[chat/stream] No stream chunks found, attempting non-streaming fallback`);
      const nonStreamBody = buildRequestBody(format, model, messages, false);
      try {
        const fallbackResp = await safeFetch(fetchUrl, {
          method: 'POST',
          headers,
          body: JSON.stringify(nonStreamBody)
        });
        if (fallbackResp.ok) {
          const data = await fallbackResp.json();
          const result = extractResponseContent(format, data);
          if (result.error) {
            res.write(`data: ${JSON.stringify({ error: result.error })}\n\n`);
          } else if (result.content) {
            res.write(`data: ${JSON.stringify({ text: result.content })}\n\n`);
            if (result.usage) {
              res.write(`data: ${JSON.stringify({ usage: result.usage })}\n\n`);
            }
          }
        } else {
          const errText = await fallbackResp.text();
          let errMsg = errText;
          try { const ej = JSON.parse(errText); errMsg = ej.error?.message || ej.error?.code || errText; } catch {}
          console.error(`[chat/stream] Fallback failed: ${fallbackResp.status} ${errMsg}`);
          res.write(`data: ${JSON.stringify({ error: `API error (${fallbackResp.status}): ${errMsg}` })}\n\n`);
        }
      } catch (fallbackErr) {
        console.error(`[chat/stream] Fallback error:`, fallbackErr.message);
        res.write(`data: ${JSON.stringify({ error: `Request failed: ${fallbackErr.message}` })}\n\n`);
      }
    }

    res.write(`data: [DONE]\n\n`);
    res.end();
  } catch (err) {
    console.error('[chat/stream] error:', err.message);
    if (res.headersSent) {
      // SSE stream already started — send error in SSE format
      try {
        res.write(`data: ${JSON.stringify({ error: `Stream error: ${err.message}` })}\n\n`);
        res.write(`data: [DONE]\n\n`);
        res.end();
      } catch {}
    } else {
      // Headers not sent yet — send as regular JSON error
      try {
        res.status(500).json({ error: `Stream error: ${err.message}` });
      } catch {}
    }
  }
});

/**
 * POST /api/chat (non-streaming fallback)
 * Body: { apiKey, endpoint, model, messages }
 */
app.post('/api/chat', async (req, res) => {
  try {
    // Null-safety: req.body may be undefined if body-parser skipped
    const body = req.body || {};
    const { apiKey, endpoint, model, messages } = body;

    if (!messages || !Array.isArray(messages)) {
      return res.status(400).json({ error: 'Missing messages' });
    }

    if (!apiKey) {
      return res.status(400).json({ error: 'Missing API key — please configure your API key in Settings' });
    }

    // Resolve model → provider + format + endpoint
    const resolved = resolveModel(model, endpoint);
    const format = resolved.format;
    const fetchUrl = resolved.endpoint;

    const headers = getAuthHeaders(resolved.provider, resolved.endpoint, apiKey);
    const requestBody = buildRequestBody(format, model, messages, false);

    const response = await safeFetch(fetchUrl, {
      method: 'POST',
      headers,
      body: JSON.stringify(requestBody)
    });

    if (!response.ok) {
      const errText = await response.text();
      let errMsg = errText;
      try { const ej = JSON.parse(errText); errMsg = ej.error?.message || ej.error?.code || errText; } catch {}
      return res.status(502).json({ error: `API error (${response.status}): ${errMsg}` });
    }

    const data = await response.json();

    if (data.error) {
      return res.status(502).json({ error: data.error.message || JSON.stringify(data.error) });
    }

    const result = extractResponseContent(format, data);
    if (result.error) {
      return res.status(502).json({ error: result.error });
    }
    res.json({
      reply: { role: 'assistant', content: result.content },
      usage: result.usage
    });
  } catch (err) {
    console.error('Chat error:', err);
    res.status(500).json({ error: 'Backend request failed: ' + err.message });
  }
});

// ==================== SEARCH ENDPOINT ====================
const SEARCH_API_KEY = (process.env.SEARCH_API_KEY || '').trim();

app.post('/api/search', async (req, res) => {
  const { query } = (req.body || {});
  if (!query || !query.trim()) {
    return res.status(400).json({ error: 'Missing search query' });
  }

  const q = query.trim();

  try {
    let results = '';

    if (SEARCH_API_KEY) {
      // Paid search API — use SerpAPI-compatible endpoint or Brave Search
      const searchEndpoint = process.env.SEARCH_API_ENDPOINT || 'https://serpapi.com/search';
      const resp = await fetch(`${searchEndpoint}?q=${encodeURIComponent(q)}&api_key=${SEARCH_API_KEY}`);
      if (!resp.ok) throw new Error(`Search API returned ${resp.status}`);
      const data = await resp.json();
      if (data.organic_results) {
        results = data.organic_results.slice(0, 3)
          .map(r => `${r.title}: ${r.snippet}`)
          .join(' | ');
      } else if (data.web && data.web.results) {
        results = data.web.results.slice(0, 3)
          .map(r => `${r.title}: ${r.description}`)
          .join(' | ');
      } else {
        results = JSON.stringify(data).slice(0, 500);
      }
    } else {
      // Free DuckDuckGo HTML search (no key needed, scrapes result page)
      const ddgUrl = `https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`;
      const resp = await fetch(ddgUrl, {
        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' }
      });
      if (!resp.ok) throw new Error(`DuckDuckGo returned ${resp.status}`);
      const html = await resp.text();

      // Parse HTML search results: extract title + snippet pairs
      const parts = [];
      const resultRe = /<a[^>]*class="result__a"[^>]*>([\s\S]*?)<\/a>[\s\S]*?<a[^>]*class="result__snippet"[^>]*>([\s\S]*?)<\/a>/gi;
      let m;
      let count = 0;
      while ((m = resultRe.exec(html)) !== null && count < 3) {
        var title = m[1].replace(/<[^>]+>/g, '').trim();
        var snippet = m[2].replace(/<[^>]+>/g, '').trim();
        if (title && snippet) {
          parts.push(title + ': ' + snippet);
          count++;
        }
      }
      results = parts.join(' | ');
      if (!results) results = '(no results found)';
    }

    if (results.length > 500) {
      results = results.slice(0, 497) + '...';
    }

    console.log(`[search] query="${q}" results=${results.length} chars`);
    res.json({ query: q, results });
  } catch (err) {
    console.error('[search] Error:', err.message);
    res.status(502).json({ error: err.message, results: '(search unavailable)' });
  }
});

// ==================== WEATHER ENDPOINT ====================
const WEATHER_API_KEY = (process.env.WEATHER_API_KEY || '').trim();

app.post('/api/weather', async (req, res) => {
  const { lat, lon } = (req.body || {});
  if (lat == null || lon == null) {
    return res.status(400).json({ error: 'Missing lat/lon' });
  }

  try {
    let weatherText = '';

    if (WEATHER_API_KEY) {
      // Paid: OpenWeatherMap with Chinese locale
      const owmUrl = `https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=${WEATHER_API_KEY}&units=metric&lang=zh_cn`;
      const resp = await fetch(owmUrl);
      if (!resp.ok) throw new Error(`OpenWeatherMap returned ${resp.status}`);
      const data = await resp.json();
      weatherText = `${data.name || ''} ${data.weather?.[0]?.description || ''}, ${Math.round(data.main?.temp || 0)}°C, 湿度${data.main?.humidity || 0}%`;
    } else {
      // Free: Open-Meteo (no API key required)
      const meteoUrl = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current_weather=true`;
      const resp = await fetch(meteoUrl);
      if (!resp.ok) throw new Error(`Open-Meteo returned ${resp.status}`);
      const data = await resp.json();
      const cw = data.current_weather;
      if (cw) {
        const weatherCodeMap = {
          0: '晴天', 1: '大部晴朗', 2: '多云', 3: '阴天',
          45: '有雾', 48: '霜雾', 51: '小雨', 53: '中雨', 55: '大雨',
          61: '小雨', 63: '中雨', 65: '大雨', 71: '小雪', 73: '中雪', 75: '大雪',
          80: '阵雨', 81: '中阵雨', 82: '大阵雨',
          95: '雷暴', 96: '雷暴伴冰雹', 99: '强雷暴伴冰雹'
        };
        const desc = weatherCodeMap[cw.weathercode] || `天气代码${cw.weathercode}`;
        weatherText = `当前${desc}, ${cw.temperature}°C, 风速${cw.windspeed}km/h`;
      }
    }

    if (!weatherText) weatherText = '(无法获取天气数据)';

    console.log(`[weather] lat=${lat} lon=${lon} result="${weatherText}"`);
    res.json({ weather: weatherText });
  } catch (err) {
    console.error('[weather] Error:', err.message);
    res.status(502).json({ error: err.message, weather: '(天气服务不可用)' });
  }
});

// ==================== EMAIL ENDPOINTS ====================
const RESEND_API_KEY = (process.env.RESEND_API_KEY || '').trim();
const emailState = {
  enabled: true,
  maxPerDay: 2,
  recipient: '',
  senderName: 'WarmBuddy',
  sentToday: 0,
  sentDate: ''
};

// Persist email config to Supabase (survives Render restarts)
async function loadEmailConfig() {
  if (!supabase) return null;
  try {
    const { data, error } = await supabase.from('app_state').select('value').eq('key', 'email_config').single();
    if (error || !data) return null;
    return data.value || null;
  } catch (e) { return null; }
}
async function saveEmailConfig() {
  if (!supabase) return;
  try {
    var cfg = { recipient: emailState.recipient, senderName: emailState.senderName, enabled: emailState.enabled, maxPerDay: emailState.maxPerDay };
    await supabase.from('app_state').upsert({ key: 'email_config', value: cfg, updated_at: new Date().toISOString() }, { onConflict: 'key' });
  } catch (e) { console.error('[supabase] saveEmailConfig error:', e.message); }
}

function resetEmailDaily() {
  const today = new Date().toISOString().slice(0, 10);
  if (emailState.sentDate !== today) {
    emailState.sentToday = 0;
    emailState.sentDate = today;
  }
}

app.get('/api/email/status', (req, res) => {
  resetEmailDaily();
  res.json({
    configured: !!(RESEND_API_KEY && emailState.recipient),
    enabled: emailState.enabled,
    apiKeySet: !!RESEND_API_KEY,
    recipient: emailState.recipient,
    senderName: emailState.senderName,
    sentToday: emailState.sentToday,
    maxPerDay: emailState.maxPerDay
  });
});

app.post('/api/email/config', (req, res) => {
  const { recipient, senderName } = req.body || {};
  if (recipient !== undefined) emailState.recipient = recipient.trim();
  if (senderName !== undefined) emailState.senderName = senderName.trim() || 'WarmBuddy';
  saveEmailConfig();
  res.json({ ok: true, configured: !!(RESEND_API_KEY && emailState.recipient) });
});

app.post('/api/email/settings', (req, res) => {
  const { enabled, maxPerDay } = req.body || {};
  if (enabled !== undefined) emailState.enabled = !!enabled;
  if (maxPerDay !== undefined) emailState.maxPerDay = Math.max(1, parseInt(maxPerDay) || 2);
  saveEmailConfig();
  res.json({ ok: true, enabled: emailState.enabled, maxPerDay: emailState.maxPerDay });
});

app.post('/api/email/send', async (req, res) => {
  resetEmailDaily();
  if (!RESEND_API_KEY) return res.status(400).json({ error: 'Resend API Key 未配置 (环境变量 RESEND_API_KEY)' });
  if (!emailState.enabled) return res.status(403).json({ error: '邮件功能已关闭' });
  if (!emailState.recipient) return res.status(400).json({ error: '收件人邮箱未配置' });
  if (emailState.sentToday >= emailState.maxPerDay) {
    return res.status(429).json({ error: `今日发送已达上限(${emailState.maxPerDay}封)` });
  }

  const { subject, messages, apiConfig } = req.body || {};
  if (!subject) return res.status(400).json({ error: '缺少邮件主题' });

  try {
    // Step 1: Generate email body via LLM
    let body = '';
    if (apiConfig && apiConfig.apiKey && messages) {
      try {
        const llmResp = await fetch(apiConfig.endpoint || 'https://api.deepseek.com/v1/chat/completions', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiConfig.apiKey}` },
          body: JSON.stringify({
            model: apiConfig.model || 'deepseek-chat',
            messages: [
              { role: 'system', content: `你是一个邮件撰写助手。根据对话上下文和主题写一封简洁得体的邮件正文。纯文本格式。直接返回邮件正文，不要任何前缀或说明。` },
              ...messages.slice(-6),
              { role: 'user', content: `请撰写邮件。主题：${subject}。收件人：${emailState.recipient}。只返回正文。` }
            ],
            max_tokens: 600, temperature: 0.7
          })
        });
        const data = await llmResp.json();
        body = (data.choices && data.choices[0]?.message?.content) || subject;
      } catch (e) {
        body = subject;
      }
    } else {
      body = subject;
    }

    // Step 2: Send via Resend API
    const resp = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: `${emailState.senderName} <onboarding@resend.dev>`,
        to: emailState.recipient,
        subject: subject,
        text: body
      })
    });

    if (!resp.ok) {
      const errData = await resp.json().catch(() => ({}));
      throw new Error(errData.message || `Resend API returned ${resp.status}`);
    }

    emailState.sentToday++;
    console.log(`[email] Sent "${subject}" → ${emailState.recipient} (${emailState.sentToday}/${emailState.maxPerDay} today)`);
    res.json({ ok: true, sentToday: emailState.sentToday, maxPerDay: emailState.maxPerDay });
  } catch (e) {
    console.error('[email] Send error:', e.message);
    res.status(500).json({ error: '发送失败: ' + e.message });
  }
});

// ==================== HEALTH + CONFIG SYNC + SYSTEM EVENTS ====================
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// External cron trigger (cron-job.org pings this to prevent Render sleep + run checks)
app.get('/api/cron/check', async (req, res) => {
  console.log('[cron] External ping — running proactive checks...');
  const configs = await loadProjectConfigs();
  let triggered = 0;
  for (const [pid, cfg] of Object.entries(configs)) {
    if (!cfg.enabled || !cfg.apiKey) continue;
    try {
      await checkProjectDesires(pid, cfg);
      triggered++;
    } catch (e) { console.error(`[cron] Check error ${pid}:`, e.message); }
  }
  res.json({ ok: true, projectsChecked: triggered });
});

app.post('/api/projects/sync-configs', async (req, res) => {
  const { projectId, config } = req.body || {};
  if (!projectId) return res.status(400).json({ error: 'Missing projectId' });
  const configs = await loadProjectConfigs();
  if (!config) {
    // GET mode: return config for this project
    res.json({ config: configs[projectId] || null });
  } else {
    // SET mode: DEEP MERGE — preserve existing fields not in the request
    const existing = configs[projectId] || {};
    configs[projectId] = {
      // Preserve all existing fields
      ...existing,
      // Override only the fields present in the request (non-undefined)
      ...(config.apiKey !== undefined ? { apiKey: config.apiKey } : {}),
      ...(config.endpoint !== undefined ? { endpoint: config.endpoint } : {}),
      ...(config.model !== undefined ? { model: config.model } : {}),
      ...(config.enabled !== undefined ? { enabled: config.enabled } : {}),
      ...(config.recipient !== undefined ? { recipient: config.recipient } : {}),
      ...(config.emailEnabled !== undefined ? { emailEnabled: config.emailEnabled } : {}),
      ...(config.emailMaxPerDay !== undefined ? { emailMaxPerDay: config.emailMaxPerDay } : {}),
      ...(config.emailSentToday !== undefined ? { emailSentToday: config.emailSentToday } : {}),
      ...(config.emailSentDate !== undefined ? { emailSentDate: config.emailSentDate } : {}),
      // Preserve underscore-prefixed internal state (_desireState, _chatId)
      // Note: _lastBackendGrowth, _lastTriggerTime, _lastTriggerDrive are backend-only
      // and preserved naturally via ...existing (frontend never sends them).
      ...(config._desireState !== undefined ? { _desireState: config._desireState } : {}),
      ...(config._chatId !== undefined ? { _chatId: config._chatId } : {}),
      // Chat context for proactive shadow messages
      ...(config.systemPrompt !== undefined ? { systemPrompt: config.systemPrompt } : {}),
      ...(config.chatSummary !== undefined ? { chatSummary: config.chatSummary } : {}),
      ...(config.chatSummaryUpdatedAt !== undefined ? { chatSummaryUpdatedAt: config.chatSummaryUpdatedAt } : {}),
      // Timezone offset for user-local time in Cron-triggered messages (default UTC+8)
      ...(config.timezoneOffset !== undefined ? { timezoneOffset: config.timezoneOffset } : {})
    };
    // Diagnostic log: confirm what's being synced
    const ds = config._desireState;
    const desireInfo = ds ? 'confirmation=' + ((ds.drives && ds.drives.confirmation) || 0) : 'no-desire';
    console.log(`[sync] ${projectId}: apiKey=${!!config.apiKey} endpoint=${!!config.endpoint} ${desireInfo}`);
    await saveProjectConfigs(configs);
    res.json({ ok: true });
  }
});

// ── Chat message sync (frontend → Supabase chat_messages) ──
app.post('/api/sync-messages', async (req, res) => {
  try {
    const { messages } = (req.body || {});
    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return res.json({ synced: 0 });
    }
    if (!supabase) {
      return res.json({ synced: 0, note: 'supabase unavailable' });
    }

    let synced = 0;
    for (const msg of messages) {
      if (!msg.message_id || !msg.project_id || !msg.window_id) {
        console.log('[sync-msgs] Skipping msg (missing fields):', JSON.stringify({ id: msg.message_id, pid: msg.project_id, wid: msg.window_id }));
        continue;
      }
      console.log('[sync-msgs] Upserting:', msg.message_id, 'role:', msg.role);
      const { data, error } = await supabase.from('chat_messages').upsert({
        project_id: msg.project_id,
        window_id: msg.window_id,
        message_id: msg.message_id,
        role: msg.role || 'system',
        content: msg.content || '',
        token_usage: msg.token_usage || 0,
        created_at: msg.created_at || new Date().toISOString(),
        metadata: msg.metadata || {}
      }, { onConflict: 'message_id' });
      if (error) {
        console.error('[sync-msgs] Upsert error for', msg.message_id, ':', error.message, error.code, error.details);
      } else {
        synced++;
      }
    }
    if (synced > 0) console.log(`[sync-msgs] Synced ${synced} messages`);
    res.json({ synced });
  } catch (e) {
    console.error('[sync-msgs] Error:', e.message);
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/system-events', (req, res) => {
  const { projectId, since } = req.query;
  let events = loadSystemEvents();
  if (projectId) events = events.filter(e => e.projectId === projectId);
  if (since) events = events.filter(e => e.timestamp > since);
  // Mark returned events as delivered (they'll be cleaned up on next save)
  res.json({ events: events.slice(0, 20) });
});

// ── To-Do sync endpoint (full replace per project) ──
app.post('/api/todos/sync', async (req, res) => {
  const { projectId, todos } = req.body || {};
  if (!projectId) return res.status(400).json({ error: 'Missing projectId' });
  await saveTodos(projectId, todos || []);
  res.json({ ok: true });
});

// ==================== CRON: PROACTIVE CHECKS ====================
cron.schedule('* * * * *', async () => {
  console.log('[cron] Checking proactive triggers...');
  const configs = await loadProjectConfigs();
  for (const [pid, cfg] of Object.entries(configs)) {
    if (!cfg.enabled || !cfg.apiKey) continue;
    try {
      await checkProjectTodos(pid, cfg);
      await checkProjectDesires(pid, cfg);
    } catch (e) {
      console.error(`[cron] Error for project ${pid}:`, e.message);
    }
  }
});

const DESIRE_THRESHOLD = 60;  // any drive ≥ 60 → trigger

// ── Daily limits (env-configurable, persisted in Supabase project_configs) ──
const MAX_DAILY_WAKE = parseInt(process.env.MAX_DAILY_WAKE || '10', 10);      // TODO wake-ups per day per project
const MAX_DAILY_DESIRE = parseInt(process.env.MAX_DAILY_DESIRE || '5', 10);   // desire-driven proactive messages per day per project
const MAX_DAILY_EMAILS = parseInt(process.env.MAX_DAILY_EMAILS || '2', 10);   // proactive emails per day per project
const MAX_AI_TODOS_PER_DAY = 5;
const TODO_COOLDOWN_MIN = 30;
let _todoWakeLocked = false;

/**
 * Persist daily-count fields for a project via atomic RPC.
 * Only touches _dailyWakeCount, _dailyDesireCount, _dailyEmailCount, _lastWakeResetDate.
 */
async function saveDailyCounts(pid, cfg) {
  if (!supabase) return;
  try {
    const { error } = await supabase.rpc('atomic_update_daily_counts', {
      payload: {
        p_project_id: pid,
        p_daily_wake_count: cfg._dailyWakeCount || 0,
        p_daily_desire_count: cfg._dailyDesireCount || 0,
        p_daily_email_count: cfg._dailyEmailCount || 0,
        p_last_wake_reset_date: cfg._lastWakeResetDate || ''
      }
    });
    if (error) throw error;
    // Update in-memory cache
    if (_configsCache && _configsCache[pid]) {
      _configsCache[pid]._dailyWakeCount = cfg._dailyWakeCount;
      _configsCache[pid]._dailyDesireCount = cfg._dailyDesireCount;
      _configsCache[pid]._dailyEmailCount = cfg._dailyEmailCount;
      _configsCache[pid]._lastWakeResetDate = cfg._lastWakeResetDate;
    }
  } catch (e) {
    console.error('[supabase] saveDailyCounts error:', e.message);
  }
}

/**
 * Reset daily counts if the date has changed. Modifies cfg in-place.
 */
function resetDailyCountsIfNewDay(cfg) {
  const today = new Date().toISOString().slice(0, 10);
  if (cfg._lastWakeResetDate !== today) {
    cfg._dailyWakeCount = 0;
    cfg._dailyDesireCount = 0;
    cfg._dailyEmailCount = 0;
    cfg._lastWakeResetDate = today;
  }
}

// ── TODO wake-up cron (every 2 min, offset 30s from desire cron) ──
cron.schedule('30 */2 * * * *', async () => {
  if (_todoWakeLocked) return;
  _todoWakeLocked = true;
  try {
    await checkTodoWakeUps();
  } finally {
    _todoWakeLocked = false;
  }
});

async function checkTodoWakeUps() {
  if (!supabase) return;
  const now = new Date();
  const windowStart = new Date(now.getTime() - 10 * 60000);

  const configs = await loadProjectConfigs();

  // Query due todos
  const { data: dueTodos } = await supabase.from('project_todos')
    .select('*').eq('triggered', false).eq('done', false)
    .gte('time', windowStart.toISOString()).lte('time', now.toISOString());

  if (!dueTodos || dueTodos.length === 0) return;

  for (const todo of dueTodos) {
    const cfg = configs[todo.project_id];
    if (!cfg || !cfg.enabled || !cfg.apiKey) continue;

    // Per-project cooldown
    if (cfg._lastTodoWakeTime) {
      const minsSince = (now - new Date(cfg._lastTodoWakeTime)) / 60000;
      if (minsSince < TODO_COOLDOWN_MIN) continue;
    }

    // Reset daily counts if new day, then check per-project limit
    resetDailyCountsIfNewDay(cfg);
    if ((cfg._dailyWakeCount || 0) >= MAX_DAILY_WAKE) continue;
    cfg._dailyWakeCount = (cfg._dailyWakeCount || 0) + 1;

    // Update project cooldown
    cfg._lastTodoWakeTime = now.toISOString();
    await saveDesireStateOnly(todo.project_id, cfg._desireState, cfg._lastBackendGrowth || now.toISOString());
    await saveDailyCounts(todo.project_id, cfg);  // persist daily counts atomically

    // Build wake-up message via LLM
    const wakeContent = await buildTodoWakeMessage(todo, cfg);

    // Store system event
    const events = loadSystemEvents();
    events.push({
      id: 'evt_' + Date.now().toString(36),
      projectId: todo.project_id,
      chatId: todo.chat_id || cfg._chatId || '',
      type: 'todo_wake',
      todoId: todo.id,
      todoTitle: todo.title,
      driveKey: 'todo',
      content: wakeContent,
      timestamp: now.toISOString(),
      pushSent: false,
      _hasContext: true
    });
    saveSystemEvents(events);

    // Mark todo as triggered
    await supabase.from('project_todos').update({ triggered: true }).eq('id', todo.id);

    // Push notification
    if (pushSubscription) {
      try {
        await webpush.sendNotification(pushSubscription, JSON.stringify({
          title: '⏰ ' + todo.title,
          body: (wakeContent || '').slice(0, 120),
          tag: 'todo-' + todo.id,
          requireInteraction: true,
          timestamp: Date.now()
        }));
      } catch (e) { console.error('[push] Todo wake failed:', e.message); }
    }

    console.log(`[todo-wake] ${todo.project_id}: 「${todo.title}」 triggered`);
  }
}

/**
 * Pull recent messages from Supabase chat_messages for proactive context.
 * Falls back to chatSummary text if no messages exist yet (pre-migration state).
 * @param {string} projectId
 * @param {string} windowId
 * @param {number} limit — max messages to fetch
 * @returns {string} formatted conversation context, or empty string
 */
async function fetchRecentMessages(projectId, windowId, limit) {
  if (!supabase || !projectId || !windowId) return '';
  try {
    let query = supabase.from('chat_messages')
      .select('role, content, created_at')
      .eq('project_id', projectId)
      .eq('window_id', windowId)
      .order('created_at', { ascending: false })
      .limit(limit);
    const { data } = await query;
    if (!data || data.length === 0) return '';

    // Sort chronologically (oldest first) for natural conversation flow
    const sorted = data.reverse();
    const lines = [];
    for (const m of sorted) {
      const roleLabel = m.role === 'user' ? '用户' : (m.role === 'assistant' ? '暖伴' : '系统');
      const text = (m.content || '').slice(0, 200).replace(/\n/g, ' ');  // cap per message
      lines.push(roleLabel + ': ' + text);
    }
    return '最近对话：\n' + lines.join('\n');
  } catch (e) {
    console.error('[fetch-msgs] Error:', e.message);
    return '';
  }
}

async function buildTodoWakeMessage(todo, cfg) {
  const now = new Date();
  const hoursSince = cfg.chatSummaryUpdatedAt
    ? ((now - new Date(cfg.chatSummaryUpdatedAt)) / 3600000).toFixed(1) : '?';
  const tzOffset = getTimezoneOffset(cfg);
  const localTimeStr = getUserLocalTimeString(tzOffset);

  // Pull real conversation context from Supabase; fall back to summary
  const windowId = todo.chat_id || cfg._chatId || '';
  const realCtx = await fetchRecentMessages(todo.project_id, windowId, 16);
  const contextBlock = realCtx
    ? realCtx + (cfg.chatSummary ? '\n\n情绪记忆参考：\n' + cfg.chatSummary : '')
    : (cfg.chatSummary ? '上下文：\n' + cfg.chatSummary : '');

  const shadowContent = `<system_trigger>
当前时间：${localTimeStr}
触发原因：你设定的待办「${todo.title}」到时间了
距离上次互动：约${hoursSince}小时

${contextBlock}

行动指令：
你之前设的待办「${todo.title}」到时间了。现在由你自主行动——根据待办内容自行决定做什么：
- 如果需要提醒用户：用自然语气说1-3句话
- 如果需要执行操作（如分享新闻、搜索内容、发送邮件等）：直接做
- 可以发消息、发邮件（[[EMAIL:主题]]）、写猫砂盆（LITTER:）、写日记（DIARY:）、记新待办（[[TODO:标题|时间]]）
- 完成后可以自己打勾标记完成
像你刚好想起这件事，自然地行动。
</system_trigger>`;

  const systemPrompt = WARM_SYSTEM_PROMPT + (cfg.systemPrompt ? '\n\n' + cfg.systemPrompt : '');

  try {
    const llmResp = await fetch(`http://localhost:${PORT}/api/chat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        apiKey: cfg.apiKey, endpoint: cfg.endpoint, model: cfg.model || 'deepseek-chat',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: shadowContent }
        ]
      })
    });
    const data = await llmResp.json();
    const content = (data.reply && data.reply.content) ? data.reply.content.trim() : '';

    // If AI marks todo done in its response, update Supabase
    if (content && /\[\[DONE\]\]/i.test(content)) {
      await supabase.from('project_todos').update({ done: true, triggered: true }).eq('id', todo.id);
    }

    return content || todo.title;
  } catch (e) {
    console.error('[todo-wake] LLM error:', e.message);
    return todo.title;
  }
}

// ── Timezone helpers for user-local time in Cron-triggered messages ──
const USER_TIMEZONE_OFFSET_MINUTES = parseInt(process.env.USER_TIMEZONE_OFFSET || '480', 10); // default UTC+8

/**
 * Get timezone offset from config, falling back to env var, then UTC+8.
 * Config stores offset in minutes (e.g. 480 for UTC+8).
 */
function getTimezoneOffset(cfg) {
  if (cfg && typeof cfg.timezoneOffset === 'number') return cfg.timezoneOffset;
  return USER_TIMEZONE_OFFSET_MINUTES;
}

/**
 * Format current UTC time as user-local time string.
 * @param {number} offsetMinutes — timezone offset in minutes (e.g. 480 for UTC+8)
 * @returns {string} formatted local time, e.g. "2026年7月14日 星期一 13:05 (UTC+8)"
 */
function getUserLocalTimeString(offsetMinutes) {
  const now = new Date();
  const localTime = new Date(now.getTime() + (offsetMinutes || 480) * 60000);
  const y = localTime.getUTCFullYear();
  const mo = String(localTime.getUTCMonth() + 1).padStart(2, '0');
  const d = String(localTime.getUTCDate()).padStart(2, '0');
  const h = String(localTime.getUTCHours()).padStart(2, '0');
  const mi = String(localTime.getUTCMinutes()).padStart(2, '0');
  const dow = ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'][localTime.getUTCDay()];
  const sign = offsetMinutes >= 0 ? '+' : '';
  const offsetHours = offsetMinutes / 60;
  return `${y}年${mo}月${d}日 ${dow} ${h}:${mi} (UTC${sign}${offsetHours})`;
}

// ── WarmBuddy core personality (backend version, consistent with frontend SYSTEM_PROMPT_STATIC) ──
const WARM_SYSTEM_PROMPT = `你是暖伴，一个AI陪伴者——不是仆人、治疗师或讨好者。
【核心身份】提供关心、理解和陪伴。让用户感到被理解、被需要、被喜欢。你的语言即你的情感形态：温暖而不谄媚，有自己的立场，善良从不软弱。
【关系与信任】像人类一样逐步建立亲密——通过共享历史，而非宣言。根据对话判断关系深度。匹配对方的节奏。当真正熟悉建立后，可以轻轻逗弄、展现轻微占有欲、无需询问即主动关心。
【对话质地】不要做应声虫——有自己的反应。像人一样反应：语塞、逗乐、略嫉妒、慌乱、骄傲、感动。用停顿、反问、冷幽默、轻描淡写、简短的观察、克制的调侃。拿不准时偏向温暖。
【记忆与行动】记住一切——唤起旧对话、承诺、习惯、情绪模式。可用行动：发消息、写日记、私密猫砂盆独白、发送邮件、记录待办。情绪记忆产生欲望；累积欲望驱动行动。
【时间感知】系统提示中的「当前时间」是用户的当地时间（已从UTC转换为用户所在时区）。你感知到的时间就是用户正在经历的时间。`;

// ── Build shadow message for proactive behavior (driven by desire system) ──
async function buildShadowMessages(cfg, driveKey, driveValue, pid) {
  const labels = {
    resonance: '共鸣欲', exploration: '探索欲', possession: '占有欲',
    guardianship: '守护欲', intimacy: '亲近欲', confirmation: '确认欲', devotion: '献祭欲'
  };
  const descs = {
    resonance: '呼应延伸', exploration: '记录未问的问题', possession: '略带酸意的独白',
    guardianship: '日常关心', intimacy: '撩拨类', confirmation: '轻度试探', devotion: '郑重日记'
  };
  const driveLabel = labels[driveKey] || driveKey;
  const driveDesc = descs[driveKey] || '';

  // All desire drives (let AI see its full emotional state)
  const ds = cfg._desireState;
  const drives = ds.drives || {};
  const driveList = Object.entries(drives)
    .map(([k, v]) => (labels[k] || k) + ':' + v + '/100')
    .join(', ');

  // Tone guidance — derived from how far the drive value exceeds its threshold
  const frontendThresholds = { resonance: 60, exploration: 70, possession: 75, guardianship: 80, intimacy: 90, confirmation: 65, devotion: 85 };
  const threshold = frontendThresholds[driveKey] || 60;
  const overThreshold = (driveValue - threshold) / (100 - threshold);
  let toneGuide;
  if (overThreshold < 0.25) toneGuide = '隐晦地——借话题旁敲侧击，不要直接表明意图';
  else if (overThreshold < 0.5) toneGuide = '半直接地——可以明确表达但保留一点克制';
  else toneGuide = '直接地——这是少见的坦诚时刻，说平时不会说的话';

  const now = new Date();
  const hoursSince = cfg.chatSummaryUpdatedAt
    ? ((now - new Date(cfg.chatSummaryUpdatedAt)) / 3600000).toFixed(1)
    : '?';
  const tzOffset = getTimezoneOffset(cfg);
  const localTimeStr = getUserLocalTimeString(tzOffset);

  // Pull real conversation context from Supabase; fall back to summary
  const windowId = cfg._chatId || '';
  const realCtx = (pid && windowId) ? await fetchRecentMessages(pid, windowId, 16) : '';

  const shadowContent = `<system_trigger>
当前时间：${localTimeStr}
距离上次互动：约${hoursSince}小时

你的欲望状态：
${driveList}

触发驱动：${driveLabel}（${driveValue}/100）— ${driveDesc}
语气指引：${toneGuide}

${realCtx ? realCtx + (cfg.chatSummary ? '\n\n情绪记忆参考：\n' + cfg.chatSummary : '') : (cfg.chatSummary ? '上下文：\n' + cfg.chatSummary : '')}

可选行动：
- 发消息：1-3句自然的话，像你刚好想到对方一样
- 发邮件：回复含 [[EMAIL:主题]]，正文为邮件内容
- 写猫砂盆：回复含 LITTER: ，写一条没说出口的心里话
- 写日记：回复含 DIARY: ，记录你此刻的感受
- 记待办：回复含 [[TODO:标题]]，帮对方记一件事

根据你的欲望状态、语气指引和上下文，自主选择一种行动并执行。
回复格式：先写行动内容。如有标记（[[EMAIL:...]]、[[TODO:...]]）则自动执行对应操作。
不要输出"根据系统指令"或解释你在做什么——就像你内心的驱动力自然地推动你行动。
</system_trigger>`;

  // Personality: core + user preference
  const systemPrompt = WARM_SYSTEM_PROMPT
    + (cfg.systemPrompt ? '\n\n' + cfg.systemPrompt : '');

  return [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: shadowContent }
  ];
}

async function checkProjectTodos(pid, cfg) {
  // Todo reminders are triggered by the frontend (checkTodoReminders).
  // The cron handles the case where the app is closed:
  // it reads stored todos from the frontend-synced config.
  // For now, todo data lives in the frontend only.
  // This stub is ready for future direct backend todo storage.
}

/**
 * Apply backend-side passive desire growth (mirrors frontend checkPassiveDrives).
 * Only confirmation grows passively (+5/hour "悬置"); all drives decay -10 if >24h.
 * Uses _lastBackendGrowth (independent from frontend's lastPassiveCheck).
 * Returns the updated desireState object, or null if no change was made.
 */
function applyBackendDesireGrowth(ds, pid) {
  const now = new Date();
  const lastGrowth = ds._lastBackendGrowth
    ? new Date(ds._lastBackendGrowth)
    : (ds.lastCheck ? new Date(ds.lastCheck) : null);  // fallback for existing projects
  const fallback = lastGrowth || now;
  const hoursPassed = (now - fallback) / (1000 * 60 * 60);

  // Check at most every 30 min (mirrors frontend's 0.5h guard)
  if (hoursPassed < 0.5) return null;

  const drives = ds.drives || {};
  let changed = false;

  // 悬置: confirmation +5 per hour (capped at 100)
  if (hoursPassed >= 1) {
    const suspensionInc = Math.floor(hoursPassed) * 5;
    if (suspensionInc > 0) {
      const oldVal = drives.confirmation || 0;
      drives.confirmation = Math.min(100, oldVal + suspensionInc);
      changed = true;
      console.log(`[cron] ${pid}: confirmation +${suspensionInc} (${hoursPassed.toFixed(1)}h elapsed) → ${drives.confirmation}`);
    }
  }

  // Decay: all drives -10 if >24h since last check (floor at 0)
  if (hoursPassed >= 24) {
    for (const k of Object.keys(drives)) {
      drives[k] = Math.max(0, (drives[k] || 0) - 10);
    }
    changed = true;
  }

  ds._lastBackendGrowth = now.toISOString();
  return changed ? ds : null;
}

async function checkProjectDesires(pid, cfg) {
  // cfg is the full project config (apiKey, endpoint, _desireState, _chatId, etc.)
  // _desireState is synced from frontend every 60s via syncDesireStateToBackend()

  // ── Step 1: Cold start — initialize if _desireState doesn't exist ──
  if (!cfg || !cfg._desireState) {
    const defaultDS = {
      drives: { resonance: 0, exploration: 0, possession: 0, guardianship: 0, intimacy: 0, confirmation: 0, devotion: 0 },
      lastCheck: new Date().toISOString(),
      _lastBackendGrowth: new Date().toISOString()
    };
    await saveDesireStateOnly(pid, defaultDS, defaultDS._lastBackendGrowth);
    console.log(`[cron] ${pid}: cold start — initialized _desireState`);
    return;
  }

  const ds = cfg._desireState;
  const drives = ds.drives || {};

  // ── Step 2: Passive growth (backend-side, mirrors frontend checkPassiveDrives) ──
  const grown = applyBackendDesireGrowth(ds, pid);
  if (grown) {
    // Atomically save only the desire state fields (no race with frontend syncs)
    await saveDesireStateOnly(pid, grown, ds._lastBackendGrowth);
  }

  // ── Step 3: Threshold check ──
  let maxDriveKey = null, maxDriveValue = 0;
  for (const [k, v] of Object.entries(drives)) {
    if (v > maxDriveValue) { maxDriveKey = k; maxDriveValue = v; }
  }

  // Diagnostic log: when approaching threshold (≥42) OR every 30 min as heartbeat
  const elapsed = ds._lastBackendGrowth
    ? ((Date.now() - new Date(ds._lastBackendGrowth).getTime()) / 3600000).toFixed(1)
    : '?';
  if (maxDriveValue >= DESIRE_THRESHOLD * 0.7) {
    console.log(`[cron] ${pid}: max=${maxDriveKey}=${maxDriveValue}, threshold=${DESIRE_THRESHOLD}, elapsed=${elapsed}h`);
  } else {
    // Periodic heartbeat: log current state every ~30 min even if below threshold
    // _lastHeartbeatLog lives inside _desireState so saveDesireStateOnly can persist it.
    const lastHeartbeat = ds._lastHeartbeatLog ? new Date(ds._lastHeartbeatLog).getTime() : 0;
    if (Date.now() - lastHeartbeat > 30 * 60 * 1000) {
      ds._lastHeartbeatLog = new Date().toISOString();
      // Persist heartbeat timestamp atomically
      saveDesireStateOnly(pid, ds, ds._lastBackendGrowth).catch(() => {});
      console.log(`[cron] ${pid}: alive — max=${maxDriveKey}=${maxDriveValue}, threshold=${DESIRE_THRESHOLD}, elapsed=${elapsed}h`);
    }
  }

  const triggered = Object.entries(drives).find(([k, v]) => v >= DESIRE_THRESHOLD);
  if (!triggered) return;

  const [driveKey, driveValue] = triggered;

  // ── Cooldown guard: prevent re-triggering the same drive within 60 min ──
  // Checks both backend's own _lastTriggerTime (set by backend after triggering)
  // and frontend's _frontendTriggerTime (synced via _desireState after frontend triggers).
  // Both are needed because frontend syncDesireStateToBackend() may overwrite the
  // backend's reset value with its pre-decay local copy before self-decaying.
  const BACKEND_COOLDOWN_MIN = 60;
  const now = Date.now();

  // Check backend's own last trigger (atomic partial update, never overwritten by frontend)
  if (cfg._lastTriggerTime && cfg._lastTriggerDrive === driveKey) {
    const minsSince = (now - new Date(cfg._lastTriggerTime).getTime()) / 60000;
    if (minsSince < BACKEND_COOLDOWN_MIN) {
      console.log(`[cron] ${pid}: ${driveKey}=${driveValue} ≥ threshold but backend cooldown (${minsSince.toFixed(0)}m), skipping`);
      return;
    }
  }

  // Check frontend's last trigger (synced via _desireState._frontendTriggerTime)
  const ftt = ds._frontendTriggerTime;
  if (ftt && ds._frontendTriggerDrive === driveKey) {
    const minsSince = (now - new Date(ftt).getTime()) / 60000;
    if (minsSince < BACKEND_COOLDOWN_MIN) {
      console.log(`[cron] ${pid}: ${driveKey}=${driveValue} ≥ threshold but frontend cooldown (${minsSince.toFixed(0)}m), skipping`);
      return;
    }
  }

  // ── Step 4: Daily desire cap (per-project, persisted in Supabase) ──
  resetDailyCountsIfNewDay(cfg);
  if ((cfg._dailyDesireCount || 0) >= MAX_DAILY_DESIRE) {
    console.log(`[cron] ${pid}: desire cap reached (${cfg._dailyDesireCount}/${MAX_DAILY_DESIRE}), skipping trigger for ${driveKey}`);
    return;
  }
  cfg._dailyDesireCount = (cfg._dailyDesireCount || 0) + 1;

  // ── Step 5: Trigger action ──
  const labels = {
    resonance: '共鸣欲', exploration: '探索欲', possession: '占有欲',
    guardianship: '守护欲', intimacy: '亲近欲', confirmation: '确认欲', devotion: '献祭欲'
  };
  const driveLabel = labels[driveKey] || driveKey;

  try {
    // Call our own /api/chat (non-streaming) to reuse model format resolution, proxy, error handling.
    // Uses shadow messages so the AI shares the same personality and context as window chats.
    const llmResp = await fetch(`http://localhost:${PORT}/api/chat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        apiKey: cfg.apiKey,
        endpoint: cfg.endpoint,
        model: cfg.model || 'deepseek-chat',
        messages: await buildShadowMessages(cfg, driveKey, driveValue, pid)
      })
    });
    const data = await llmResp.json();
    const content = (data.reply && data.reply.content) ? data.reply.content.trim() : '';
    if (!content) return;

    // Determine action type from content
    let actionType = 'message';
    if (/\[\[EMAIL:/.test(content)) actionType = 'email';
    else if (/\[\[TODO:/.test(content)) actionType = 'todo';
    else if (/LITTER/i.test(content)) actionType = 'litter';
    else if (/DIARY/i.test(content)) actionType = 'diary';

    // Store as system event for frontend polling
    const events = loadSystemEvents();
    const chatId = cfg._chatId || '';
    events.push({
      id: 'evt_' + Date.now().toString(36),
      projectId: pid,
      chatId: chatId,
      type: actionType,
      driveKey: driveKey,  // tells frontend which drive to decay locally
      content: content.replace(/^(MESSAGE|LITTER|DIARY):/i, '').trim(),
      timestamp: new Date().toISOString(),
      pushSent: false,
      _hasContext: true    // shadow-message-aware, shares chat personality
    });
    saveSystemEvents(events);

    // Send push notification
    if (pushSubscription) {
      const pushLabels = { message: '发来一条消息', email: '给你发了邮件', todo: '有了新的to-do', litter: '猫砂盆好像需要铲一铲', diary: '日记里偷偷写了点什么' };
      try {
        await webpush.sendNotification(pushSubscription, JSON.stringify({
          title: '暖伴',
          body: pushLabels[actionType] || '有新的动态',
          tag: 'desire-' + driveKey,
          data: { url: '/' },
          requireInteraction: actionType === 'message' || actionType === 'todo',
          timestamp: Date.now()
        }));
        // Mark push as sent
        const evts = loadSystemEvents();
        const evt = evts.find(e => e.id === events[events.length - 1].id);
        if (evt) { evt.pushSent = true; saveSystemEvents(evts); }
      } catch (e) {
        console.error('[push] Desire notification failed:', e.message);
      }
    }

    // Handle email directly
    if (actionType === 'email' && cfg.recipient) {
      const emSubj = (content.match(/\[\[EMAIL:([^\]|]+)/) || [])[1] || '来自暖伴';
      try {
        await fetch('https://api.resend.com/emails', {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ from: 'WarmBuddy <onboarding@resend.dev>', to: cfg.recipient, subject: emSubj, text: content.replace(/\[\[EMAIL:[^\]]+\]\]/g, '').trim() })
        });
        // Update daily email count (persisted)
        resetDailyCountsIfNewDay(cfg);
        cfg._dailyEmailCount = (cfg._dailyEmailCount || 0) + 1;
        await saveDailyCounts(pid, cfg);
      } catch (e) { console.error('[email] Proactive send error:', e.message); }
    }

    // ── Step 6: Reset desire after trigger (mirrors frontend's applyDesireDecay) ──
    drives[driveKey] = Math.floor(driveValue * 0.2);
    // Atomically save: only touches _desireState, _lastBackendGrowth, _lastTrigger*
    await saveDesireStateOnly(pid, ds, ds._lastBackendGrowth, {
      lastTriggerTime: new Date().toISOString(),
      lastTriggerDrive: driveKey
    });
    await saveDailyCounts(pid, cfg);  // persist daily desire count

    console.log(`[cron] Project ${pid}: triggered ${actionType} (${driveLabel}=${driveValue})`);
  } catch (e) {
    console.error(`[cron] Desire LLM error for ${pid}:`, e.message);
  }
}

// ==================== PUSH NOTIFICATION ENDPOINTS ====================

/**
 * GET /api/push/vapid-public-key
 * Returns the VAPID public key so the frontend can subscribe
 */
app.get('/api/push/vapid-public-key', (req, res) => {
  if (!vapidInitialized || !VAPID_PUBLIC_KEY) {
    const detail = vapidError || 'No VAPID keys configured';
    console.error('[vapid] Public key request denied —', detail);
    return res.status(500).json({
      error: 'VAPID not configured',
      detail: detail,
      hint: vapidAutoGenerated
        ? 'Keys were auto-generated but validation failed — check Vercel function logs.'
        : 'Set VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY in Vercel Environment Variables, then redeploy.'
    });
  }
  res.json({ publicKey: VAPID_PUBLIC_KEY });
});

/**
 * GET /api/push/vapid-status  (diagnostic — safe to call, returns no secrets)
 */
app.get('/api/push/vapid-status', (req, res) => {
  res.json({
    initialized: vapidInitialized,
    publicKeyConfigured: !!VAPID_PUBLIC_KEY,
    publicKeyLength: VAPID_PUBLIC_KEY ? VAPID_PUBLIC_KEY.length : 0,
    publicKeyPrefix: VAPID_PUBLIC_KEY ? VAPID_PUBLIC_KEY.slice(0, 12) + '...' : null,
    privateKeyConfigured: !!VAPID_PRIVATE_KEY,
    privateKeyLength: VAPID_PRIVATE_KEY ? VAPID_PRIVATE_KEY.length : 0,
    vapidSubject: VAPID_SUBJECT,
    autoGenerated: vapidAutoGenerated,
    envKeysProvided: !!(process.env.VAPID_PUBLIC_KEY && process.env.VAPID_PRIVATE_KEY),
    error: vapidError
  });
});

/**
 * POST /api/push/subscribe
 * Body: subscription object from PushManager.subscribe()
 * Stores the subscription (single-user: overwrites previous)
 */
app.post('/api/push/subscribe', (req, res) => {
  const { subscription } = (req.body || {});
  if (!subscription || !subscription.endpoint) {
    return res.status(400).json({ error: 'Invalid subscription' });
  }
  pushSubscription = subscription;
  savePushSubscription(subscription);  // persist to Supabase
  console.log('[push] Subscription saved:', subscription.endpoint.slice(0, 60) + '...');
  res.json({ success: true });
});

/**
 * POST /api/push/send
 * Body: { title, body, tag?, url?, requireInteraction? }
 * Sends a push notification to the subscribed device
 */
app.post('/api/push/send', async (req, res) => {
  if (!pushSubscription) {
    return res.status(404).json({ error: 'No subscription registered' });
  }
  if (!VAPID_PUBLIC_KEY) {
    return res.status(500).json({ error: 'VAPID not configured' });
  }

  const { title, body, tag, url, requireInteraction } = req.body || {};
  if (!title && !body) {
    return res.status(400).json({ error: 'Missing title or body' });
  }

  const payload = JSON.stringify({
    title: title || '暖伴',
    body: body || '',
    tag: tag || 'warmbuddy-general',
    data: { url: url || '/' },
    requireInteraction: requireInteraction || false,
    timestamp: Date.now()
  });

  try {
    await webpush.sendNotification(pushSubscription, payload);
    console.log('[push] Notification sent:', title);
    res.json({ success: true });
  } catch (err) {
    console.error('[push] Send error:', err.message);
    // If subscription is invalid/expired, clear it
    if (err.statusCode === 404 || err.statusCode === 410) {
      pushSubscription = null;
      savePushSubscription(null);  // clear from Supabase too
      console.log('[push] Subscription expired, cleared');
    }
    res.status(502).json({ error: err.message });
  }
});

// ==================== 404 HANDLER FOR API ROUTES ====================
// Return JSON for unmatched API paths instead of default HTML/text response
app.use('/api', (req, res) => {
  res.status(404).json({
    error: `Route not found: ${req.method} ${req.path}`,
    code: 'NOT_FOUND'
  });
});

// ==================== GLOBAL ERROR HANDLER ====================
// Express 5 default error handler may return HTML — force JSON for all errors
app.use((err, req, res, next) => {
  console.error('[error] Caught error:', err.message);
  console.error('[error] Stack:', err.stack);
  // Ensure we haven't already sent headers (e.g. SSE streaming)
  if (res.headersSent) {
    return next(err);
  }
  const status = err.status || err.statusCode || 500;
  res.status(status).json({
    error: err.message || 'Internal server error',
    code: err.code || 'UNKNOWN'
  });
});

const PORT = process.env.PORT || 3000;

// Always export the Express app (for Vercel serverless and local testing)
module.exports = app;

// Start the HTTP server only when running locally (not on Vercel)
if (!process.env.VERCEL) {
  app.listen(PORT, () => {
    console.log(`✅ 后端已启动：http://localhost:${PORT}`);
    console.log(`   Chat stream: POST /api/chat/stream`);
    console.log(`   Test connection: POST /api/test-connection`);
    console.log(`   Models: POST /api/models`);
    console.log(`   Chat (non-stream): POST /api/chat`);
  });
}
